apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-operator
  namespace: argocd
spec:
  destination:
    namespace: tekton-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: installCRDs
        value: "true"
    path: chart
    repoURL: https://github.com/tektoncd/operator.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true