# code: language=ansible
---

- name: "Argo admin user setup"
  run_once: true
  block:
    - name: "Bcrypt new argocd password"
      ansible.builtin.shell:
        cmd: argocd account bcrypt --password "{{ argocd_new_admin_password }}"
      register: argocd_admin_pw_bcrypted

    - name: "Set new argocd admin password"
      ansible.builtin.shell:
        cmd: "kubectl -n argocd patch secret argocd-secret -p '{\"stringData\": {\"admin.password\": \"{{ argocd_admin_pw_bcrypted.stdout }}\", \"admin.passwordMtime\": \"'$(date +%FT%T%Z)'\"}}'"
